Add turkish locale
TigoDevelopment/TigoAntiCheat pull request #21
Opened 2020-02-12 19:54 UTC by yagizher

Meow... meow and meow meow

2020-02-12 19:56 UTC, yagizher commented
I honestly dont know what i did in the last commit. You are free to test it or smth.

2020-02-12 23:12 UTC, ThymonA requested changes
Undo this change, we are dealing with a while loop and not an if statement.

2020-02-12 23:12 UTC, TigoDevelopment commented on client/main.lua
> +            print("Whoopsie something went really wrong")
Undo this change, we are dealing with a while loop and not an if statement.

2020-02-13 16:49 UTC, yagizher reviewed
done

2020-02-13 23:01 UTC, merged

2020-02-13 23:01 UTC, TigoDevelopment commented
Thanks for adding this!